### PR TITLE
Use java kids

### PR DESCRIPTION
**Pull request by AndrewDisco**

### CODE REVIEW

**Comment by EmeraldMike** [comment]
WTF
Not only is that bad formatting that will also break all the code.

**Comment by AndrewDisco** [comment]
hahah java go br

**Comment by AndrewDisco** [comment]
it wont break code tho, its just a readme

**Comment by XFaonAE** [comment]
> it wont break code tho, its just a readme

technically your right, but when people read it, it's going to cause people to write broken code

**Pull request closed without merging**
