### PR TITLE
Added Server Identifier

### PR DESCRIPTION
**Pull request by EmeraldMike**

### CODE REVIEW

**Comment by DarkMalwre** [comment]
typos sir

**Comment by XFaonAE** [comment]
So it this to identify a list of servers? I don't think something like this should be added as it then prevents the user from extending the Server class

**Comment by EmeraldMike** [comment]
No just a single server

**Comment by XFaonAE** [comment]
It seems like this was created for multi node. But Oxide doesnt support that anymore, instead we encourage a different method of scaling which is much better

**Pull request closed without merging**
